seurl = "http://www.bencheng.net"
title = "Ben Cheng"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "geekythings"
googleAnalytics = "UA-2687665-1"

[params]
    author = "Ben Cheng"
    info = "Founder, Coder, Activist"
    description = "Ben Cheng's Personal Site"
    keywords = "blog,developer,personal,startups"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "The three most harmful addictions are heroin, carbon hydrates, and a monthly salary."

    hidecredits = false
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

[params.fathomAnalytics]
    siteID = "1"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/chpapa/"
[[params.social]]
    name = "Facebook"
    icon = "fa fa-facebook fa-2x"
    weight = 2
    url = "https://facebook.com/chpapa"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/chpapa"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "README"
    weight = 3
    url = "https://oursky.notion.site/Ben-README-02bd22c28e1f41e49921c07d99169639"
# [[menu.main]]
#    name = "Newsletter"
#    weight = 4
#    url = "https://bencheng.substack.com/"
